apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: revhire-app
  name: sqlite-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/outpost-443210/zones/us-west1-a/disks/csi-driver
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-standard
  volumeMode: Filesystem
